# Site settings
title: "Hexife"
description: "Hexife's personal page"
baseurl: "/" # the subpath of your site, e.g. /blog
url: "http://hexife.kr" # "localhost:3000" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: "Hexife"
user_description: "Bicycle rights irony actually neutra typewriter lyft. Man bun taxidermy put a bird on it, umami yr ramps pop-up ugh bushwick chia lo-fi. Occupy bitters pour-over snackwave you probably haven't heard of them small batch. Cornhole mustache man bun letterpress echo park VHS."
user_title: "Security Reseacher"
email: "hexife at nate.com"
twitter_username: ""
github_username:  "hexife"
gplus_username:  ""

# Google-analytics
google-analytics:
  id: ""

exclude: ['package.json', 'src' , 'node_modules']
