# Site settings
title: "Hexife"
description: "Hexife's personal page"
baseurl: "/" # the subpath of your site, e.g. /blog
url: "http://hexife.kr" # "localhost:3000" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: "Hexife"
user_description: ""
user_title: "Security Reseacher"
email: "hexife at nate.com"
twitter_username: ""
github_username:  "hexife"

# Google-analytics
google-analytics:
  id: ""

exclude: ['package.json', 'src' , 'node_modules']
